services:
  postgres:
    image: postgres:16-alpine
    container_name: sentry-study-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: study
      POSTGRES_PASSWORD: study1234
      POSTGRES_DB: sentry_study
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
